theme: jekyll-theme-cayman
title: "Reddit Bots"
description: "A collection of my reddit bots"
author: "Ricardo Rodriguez"
author_email: "rodriguez.ricardo.ch@outlook.com"
url: "https://github.com/coding-poetry/reddit-bots/archive/master.zip"
show_downloads: true
