theme: jekyll-theme-cayman
title: "Github page without download link"
description: "No way to directly download .zip help"
author: "Ricardo Rodriguez"
author_email: "rodriguez.ricardo.ch@outlook.com"
url: "https://github.com/coding-poetry/reddit-bots/archive/master.zip"
